all: clear clean compile run

clear:
	@clear



compile: 200104004012.c
	@gcc -c 200104004012.c
	@gcc -o lab12.out 200104004012.o

	
run:
	./lab12.out	
	
	
clean: 

	@rm -f *.o
	@rm -f lab12.out
	@rm -f lab12.o
	
