all: clear clean compile run

clear:
	@clear



compile: 200104004012.c
	@gcc -c 200104004012.c
	@gcc -o lab13.out 200104004012.o

	
run:
	./lab13.out	
	
	
clean: 

	@rm -f *.o
	@rm -f lab13.out
	@rm -f lab13.o
	
